### PR TITLE
docs: add Japanese README

### PR DESCRIPTION
**Pull request by eltociear**
I created Japanese translated README.

### CODE REVIEW

**Comment by chg0901** [comment]
thank you for your pr, we will check it asap~

**Comment by chg0901** [comment]
I  use kimi in Chinese to review these three readme files, here is the report, please follow the same or similar format to review the readme files in other LLMs. Best Regrads~

https://kimi.moonshot.cn/share/cq8ueg2vk6g2knns2nb0

**Comment by chg0901** [comment]
> I use kimi in Chinese to review these three readme files, here is the report, please follow the same or similar format to review the readme files in other LLMs. Best Regrads~
> 
> https://kimi.moonshot.cn/share/cq8ueg2vk6g2knns2nb0


@MING-ZCH Hi, ChenHao, is this PR ready to merge? (Even though I just merged the EmoLLM V3.0 updates)

@eltociear Could you please check and add the new translations related to #277 and #274? Thank you very much.

By the way, may I ask where you are from? We would like to invite you to join our developers' community.

Best Regards~

**Comment by MING-ZCH** [comment]
This PR is meaningful, and we need to trouble @eltociear to update to the latest version, thanks！

**Review by MING-ZCH — COMMENTED** [review]
Please update to the latest version, thanks！

**Comment by aJupyter** [comment]
Thank you for your contribution, we need you to update the Japanese version to the latest version, special thanks.

**Review by chg0901 — APPROVED** [review]

**Pull request merged**
